/* eslint-disable no-undef */
describe('Blog app', function () {
  beforeEach(function () {
    cy.request('POST', 'http://localhost:3003/api/testing/reset')
    cy.visit('http://localhost:3000')
  })

  it('Login form is shown', function () {
    cy.get('#username').should('be.visible')
    cy.get('#password').should('be.visible')
  })
  describe('Login', function () {
    it('succeeds with correct credentials', function () {
      cy.get('#showRegister').click()
      cy.get('#registerUsername').type('test')
      cy.get('#registerPassword').type('test123')
      cy.get('#registerDisplayName').type('123')
      cy.get('#confirmRegister').click()
      cy.get('#username').type('test')
      cy.get('#password').type('test123')
      cy.get('#login-button').click()
      cy.contains('123 logged in')
    })

    it('fails with wrong credentials', function () {
      cy.get('#username').type('test')
      cy.get('#password').type('test123')
      cy.get('#login-button').click()
      cy.contains('wrong credentials')
    })
  })
  describe('When logged in', function () {
    beforeEach(function () {
      cy.get('#showRegister').click()
      cy.get('#registerUsername').type('test')
      cy.get('#registerPassword').type('test123')
      cy.get('#registerDisplayName').type('123')
      cy.get('#confirmRegister').click()
      cy.get('#username').type('test')
      cy.get('#password').type('test123')
      cy.get('#login-button').click()

    })

    it('A blog can be created', function () {
      cy.get('#showBlogForm').click()
      cy.get('#blog-title').type('Testing')
      cy.get('#blog-author').type('Cypress')
      cy.get('#blog-url').type('google.com')
      cy.get('#postBlog').click()

      cy.contains('Added Testing from Cypress')
      cy.reload()
      cy.get('#blogDiv').should('be.visible')
    })
    it('A blog can be deleted', function () {
      cy.get('#showBlogForm').click()
      cy.get('#blog-title').type('Testing')
      cy.get('#blog-author').type('Cypress')
      cy.get('#blog-url').type('google.com')
      cy.get('#postBlog').click()
      cy.reload()
      cy.get('#logout').click()
      cy.get(':nth-child(1) > :nth-child(1) > :nth-child(1) > button').click()
      cy.get('#username').type('test')
      cy.get('#password').type('test123')
      cy.get('#login-button').click().then(() => {
        cy.wait(300)
        cy.get('#showBlog').click({ waitForAnimations: true })
        cy.get('#removeBlog').click()
        cy.on('window:confirm', () => true)
        cy.get('#allblogs').should('be.empty')
      })
    })
    it('The blogs are sorted based on the amount of likes', () => {
      cy.get('#showBlogForm').click()
      cy.get('#blog-title').type('Testing')
      cy.get('#blog-author').type('Cypress')
      cy.get('#blog-url').type('google.com')
      cy.get('#postBlog').click()
      cy.wait(500)
      cy.get('#showBlogForm').click()
      cy.get('#blog-title').clear().type('Testing2')
      cy.get('#blog-author').clear().type('Cypress2')
      cy.get('#blog-url').clear().type('google.com')
      cy.get('#postBlog').click()
      cy.wait(500)
      cy.get('#showBlogForm').click()
      cy.get('#blog-title').clear().type('Testing3')
      cy.get('#blog-author').clear().type('Cypress3')
      cy.get('#blog-url').clear().type('google.com')
      cy.get('#postBlog').click()
      cy.wait(500)
      cy.get('#logout').click()
      cy.wait(250)
      cy.get('#username').type('test')
      cy.get('#password').type('test123')
      cy.get('#login-button').click()
      cy.wait(250)
      cy.get(':nth-child(2) > .hiddenByDefault > #blogDiv > :nth-child(1) > #showBlog').click()
      cy.get(':nth-child(2) > .hiddenByDefault > #blogDiv > .togglableContent > :nth-child(2)').click()
      cy.get('#allblogs > :nth-child(1) > :nth-child(1)').contains('Testing2')
      cy.get('#allblogs > :nth-child(3) > :nth-child(1)').contains('Testing3')
      cy.wait(250)
      cy.get(':nth-child(3) > .hiddenByDefault > #blogDiv > :nth-child(1) > #showBlog').click()
      cy.get(':nth-child(3) > .hiddenByDefault > #blogDiv > .togglableContent > :nth-child(2)').click()
      cy.wait(250)
      cy.get(':nth-child(2) > .hiddenByDefault > #blogDiv > :nth-child(1) > #showBlog').click()
      cy.get(':nth-child(2) > .hiddenByDefault > #blogDiv > .togglableContent > :nth-child(2)').click()
      cy.wait(200)
      cy.get('#allblogs > :nth-child(1) > :nth-child(1)').contains('Testing3')
    })
  })
})
